// <auto-generated />
using System;
using Jilo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jilo.Migrations
{
    [DbContext(typeof(JiloContext))]
    [Migration("20260417161441_UpdateContext")]
    partial class UpdateContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jilo.Models.AdversmetUser", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("IdGame")
                        .HasColumnType("integer")
                        .HasColumnName("id_game");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_create");

                    b.Property<string>("Discription")
                        .HasColumnType("character varying")
                        .HasColumnName("discription");

                    b.Property<int?>("IdSecondUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_second_user");

                    b.Property<string>("NameSecondUser")
                        .HasColumnType("character varying")
                        .HasColumnName("name_second_user");

                    b.HasKey("IdUser", "IdGame");

                    b.HasIndex("IdGame");

                    b.HasIndex(new[] { "IdUser", "IdGame" }, "adversmet_user_unique")
                        .IsUnique();

                    b.ToTable("adversmet_user", (string)null);
                });

            modelBuilder.Entity("Jilo.Models.Comm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Comm1")
                        .HasColumnType("character varying")
                        .HasColumnName("comm");

                    b.Property<double?>("Grade")
                        .HasColumnType("double precision")
                        .HasColumnName("grade");

                    b.Property<int?>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int?>("Targetuser")
                        .HasColumnType("integer")
                        .HasColumnName("targetuser");

                    b.HasKey("Id")
                        .HasName("comm_pk");

                    b.HasIndex("IdUser");

                    b.ToTable("comm", (string)null);
                });

            modelBuilder.Entity("Jilo.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("character varying")
                        .HasColumnName("avatar");

                    b.Property<string>("Discrip")
                        .HasColumnType("character varying")
                        .HasColumnName("discrip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("games_pk");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Jilo.Models.GamesUser", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("IdGame")
                        .HasColumnType("integer")
                        .HasColumnName("id_game");

                    b.Property<string>("Rank")
                        .HasColumnType("character varying")
                        .HasColumnName("rank");

                    b.Property<string>("Role")
                        .HasColumnType("character varying")
                        .HasColumnName("role");

                    b.Property<string>("TimeInGame")
                        .HasColumnType("character varying")
                        .HasColumnName("time_in_game");

                    b.HasKey("IdUser", "IdGame")
                        .HasName("games_user_pk");

                    b.HasIndex("IdGame");

                    b.ToTable("games_user", (string)null);
                });

            modelBuilder.Entity("Jilo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("character varying")
                        .HasColumnName("avatar");

                    b.Property<string>("Comm")
                        .HasColumnType("character varying")
                        .HasColumnName("comm");

                    b.Property<DateOnly>("DataRegistration")
                        .HasColumnType("date")
                        .HasColumnName("data_registration");

                    b.Property<string>("Discription")
                        .HasColumnType("character varying")
                        .HasColumnName("discription");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<double?>("Grade")
                        .HasColumnType("double precision")
                        .HasColumnName("grade");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasDefaultValueSql("'\"USER\"'::character varying");

                    b.Property<double?>("Socialcredits")
                        .HasColumnType("double precision")
                        .HasColumnName("socialcredits");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("user_pk");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Jilo.Models.AdversmetUser", b =>
                {
                    b.HasOne("Jilo.Models.Game", "IdGameNavigation")
                        .WithMany()
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("adversmet_user_games_fk");

                    b.HasOne("Jilo.Models.User", "IdUserNavigation")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("adversmet_user_user_fk");

                    b.Navigation("IdGameNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Jilo.Models.Comm", b =>
                {
                    b.HasOne("Jilo.Models.User", "IdUserNavigation")
                        .WithMany("Comms")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comm_user_fk");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Jilo.Models.GamesUser", b =>
                {
                    b.HasOne("Jilo.Models.Game", "IdGameNavigation")
                        .WithMany("GamesUsers")
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("games_user_games_fk");

                    b.HasOne("Jilo.Models.User", "IdUserNavigation")
                        .WithMany("GamesUsers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("games_user_user_fk");

                    b.Navigation("IdGameNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Jilo.Models.Game", b =>
                {
                    b.Navigation("GamesUsers");
                });

            modelBuilder.Entity("Jilo.Models.User", b =>
                {
                    b.Navigation("Comms");

                    b.Navigation("GamesUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
